language: go
go: "1.18"

os: linux
dist: focal
arch:
  - amd64
  - ppc64le
  - s390x
  - arm64

before_install: nvm install 12

addons:
  apt:
    packages:
    - maven

script: make clean test CC=clang

cache:
  directories:
  - $HOME/.m2
